# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: brakeman_test_development
  username: postgres
  password: postgres
    
test:
  <<: *default
  database: brakeman_test_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: brakeman_test_production
  username: brakeman_test
  password: <%= ENV['BRAKEMAN_TEST_DATABASE_PASSWORD'] %>
